INSERT INTO usuarios_cidade(cidade) VALUES ('APUCARANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ARAPONGAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOM SUCESSO');
INSERT INTO usuarios_cidade(cidade) VALUES ('BORRAZOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('CALIFORNIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMBIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CRUZMALTINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('FAXINAL');
INSERT INTO usuarios_cidade(cidade) VALUES ('JANDAIA DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('KALORE');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARILANDIA SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARUMBI');
INSERT INTO usuarios_cidade(cidade) VALUES ('MAUA DA SERRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVO ITACOLOMI');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO BOM');
INSERT INTO usuarios_cidade(cidade) VALUES ('SABAUDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ADRIANOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALM TAMANDARE');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOCAIUVA DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPINA GDE SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPO MAGRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CERRO AZUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('COLOMBO');
INSERT INTO usuarios_cidade(cidade) VALUES ('DOUTOR ULYSSES');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAPERUCU');
INSERT INTO usuarios_cidade(cidade) VALUES ('PINHAIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PIRAQUARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUATRO BARRAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO BRANCO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('TUNAS DO PARANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('AGUDOS DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('ARAUCARIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('BALSA NOVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPO LARGO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPO TENENTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CONTENDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('FAZ RIO GRANDE');
INSERT INTO usuarios_cidade(cidade) VALUES ('LAPA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MANDIRITUBA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PIEN');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUITANDINHA');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO NEGRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JOSE PINHAIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('TIJUCAS DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('A CHATEAUBRIAND');
INSERT INTO usuarios_cidade(cidade) VALUES ('BRASILANDIA SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('FORMOSA D OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('IRACEMA D OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('JESUITAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA AURORA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TUPASSI');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALTAM DO PARANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ARARUNA');
INSERT INTO usuarios_cidade(cidade) VALUES ('BARBOSA FERRAZ');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPINA LAGOA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPO MOURAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CORUMBATAI SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('ENG BELTRAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('FAROL');
INSERT INTO usuarios_cidade(cidade) VALUES ('FENIX');
INSERT INTO usuarios_cidade(cidade) VALUES ('IRETAMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('LUIZIANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MAMBORE');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA CANTU');
INSERT INTO usuarios_cidade(cidade) VALUES ('PEABIRU');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUINTA DO SOL');
INSERT INTO usuarios_cidade(cidade) VALUES ('RONCADOR');
INSERT INTO usuarios_cidade(cidade) VALUES ('ANAHY');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOA V APARECIDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('BRAGANEY');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAFELANDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPO BONITO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAP L MARQUES');
INSERT INTO usuarios_cidade(cidade) VALUES ('CASCAVEL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CATANDUVAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('CEU AZUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CORBELIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUARANIACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('IBEMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IGUATU');
INSERT INTO usuarios_cidade(cidade) VALUES ('LINDOESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA LUCIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('STA TEREZA OEST');
INSERT INTO usuarios_cidade(cidade) VALUES ('T BARRAS DO PR');
INSERT INTO usuarios_cidade(cidade) VALUES ('VERA C DO OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CIANORTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CIDADE GAUCHA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUAPOREMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('INDIANOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('JAPURA');
INSERT INTO usuarios_cidade(cidade) VALUES ('JUSSARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('RONDON');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAO MANOEL PR');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAO TOME');
INSERT INTO usuarios_cidade(cidade) VALUES ('TAPEJARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TERRA BOA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TUNEIRAS OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('ASSAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('BANDEIRANTES');
INSERT INTO usuarios_cidade(cidade) VALUES ('CONGONHINHAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('CORN PROCOPIO');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAMBARACA');
INSERT INTO usuarios_cidade(cidade) VALUES ('JATAIZINHO');
INSERT INTO usuarios_cidade(cidade) VALUES ('LEOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('N STA BARBARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA AM COLINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA FATIMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('RANCHO ALEGRE');
INSERT INTO usuarios_cidade(cidade) VALUES ('S CEC DO PAVAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JERON SERRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('S SEB AMOREIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA AMELIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA MARIANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SERTANEJA');
INSERT INTO usuarios_cidade(cidade) VALUES ('STO A PARAISO');
INSERT INTO usuarios_cidade(cidade) VALUES ('URAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('CURITIBA');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOA ESP IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('CRUZEIRO IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('DOIS VIZINHOS');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA E SUDOESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA P IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JORGE D OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('SALTO LONTRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('FOZ DO IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAIPULANDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MATELANDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MEDIANEIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MISSAL');
INSERT INTO usuarios_cidade(cidade) VALUES ('RAMILANDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('S MIG IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('SERRAN. IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('STA TER ITAIPU');
INSERT INTO usuarios_cidade(cidade) VALUES ('AMPERE');
INSERT INTO usuarios_cidade(cidade) VALUES ('BARRACAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('BELA V. CAROBA');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOM JESUS SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAPANEMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ENEAS MARQUES');
INSERT INTO usuarios_cidade(cidade) VALUES ('FLOR SERRA SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('FRANC BELTRAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('MANFRINOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARMELEIRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('PEROLA DO OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('PINHAL S BENTO');
INSERT INTO usuarios_cidade(cidade) VALUES ('PLANALTO');
INSERT INTO usuarios_cidade(cidade) VALUES ('PRANCHITA');
INSERT INTO usuarios_cidade(cidade) VALUES ('REALEZA');
INSERT INTO usuarios_cidade(cidade) VALUES ('RENASCENCA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SALGADO FILHO');
INSERT INTO usuarios_cidade(cidade) VALUES ('STA IZABEL OEST');
INSERT INTO usuarios_cidade(cidade) VALUES ('STO A SUDOESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('VERE');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOA ESPERANCA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GOIOERE');
INSERT INTO usuarios_cidade(cidade) VALUES ('JANIOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('JURANDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARILUZ');
INSERT INTO usuarios_cidade(cidade) VALUES ('MOREIRA SALES');
INSERT INTO usuarios_cidade(cidade) VALUES ('Q. CENTENARIO');
INSERT INTO usuarios_cidade(cidade) VALUES ('RANCHO A OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('UBIRATA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMPINA SIMAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CANDOI');
INSERT INTO usuarios_cidade(cidade) VALUES ('FOZ DO JORDAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('GOIOXIM');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUARAPUAVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PINHAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('RESERVA IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('TURVO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CONS MAIRINCK');
INSERT INTO usuarios_cidade(cidade) VALUES ('FIGUEIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUAPIRAMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IBAITI');
INSERT INTO usuarios_cidade(cidade) VALUES ('JABOTI');
INSERT INTO usuarios_cidade(cidade) VALUES ('JAPIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PINHALAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('SIQUEIRA CAMPOS');
INSERT INTO usuarios_cidade(cidade) VALUES ('TOMAZINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('F. PINHEIRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUAMIRANGA');
INSERT INTO usuarios_cidade(cidade) VALUES ('INACIO MARTINS');
INSERT INTO usuarios_cidade(cidade) VALUES ('IRATI');
INSERT INTO usuarios_cidade(cidade) VALUES ('MALLET');
INSERT INTO usuarios_cidade(cidade) VALUES ('PRUDENTOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('REBOUCAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO AZUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('TEIXEIRA SOARES');
INSERT INTO usuarios_cidade(cidade) VALUES ('ARAPUA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ARIRANHA IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('CANDIDO ABREU');
INSERT INTO usuarios_cidade(cidade) VALUES ('GODOY MOREIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GRANDES RIOS');
INSERT INTO usuarios_cidade(cidade) VALUES ('IVAIPORA');
INSERT INTO usuarios_cidade(cidade) VALUES ('JARDIM ALEGRE');
INSERT INTO usuarios_cidade(cidade) VALUES ('LIDIANOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('LUNARDELLI');
INSERT INTO usuarios_cidade(cidade) VALUES ('MANOEL RIBAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO BRANCO DO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO BRANCO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('ROSARIO DO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('S PEDRO DO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAO JOAO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('ABATIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ANDIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('BARRA DO JACARE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMBARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CARLOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('JACAREZINHO');
INSERT INTO usuarios_cidade(cidade) VALUES ('JOAQUIM TAVORA');
INSERT INTO usuarios_cidade(cidade) VALUES ('JUNDIAI DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUATIGUA');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIB DO PINHAL');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIBEIRAO CLARO');
INSERT INTO usuarios_cidade(cidade) VALUES ('STO ANT PLATINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CANTAGALO');
INSERT INTO usuarios_cidade(cidade) VALUES ('DIAMANTE DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('ESP.ALTO IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('LARANJ DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARQUINHO');
INSERT INTO usuarios_cidade(cidade) VALUES ('N. LARANJEIRAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PORTO BARREIRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUEDAS DO IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUEDAS IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('RIO B IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('VIRMOND');
INSERT INTO usuarios_cidade(cidade) VALUES ('DIAMANTE NORTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAUNA DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('LOANDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARILENA');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA LONDRINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PLANALTINA PR');
INSERT INTO usuarios_cidade(cidade) VALUES ('PORTO RICO');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUERENCIA NORTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('S C M CASTELO');
INSERT INTO usuarios_cidade(cidade) VALUES ('S PEDRO DO PR');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA MONICA');
INSERT INTO usuarios_cidade(cidade) VALUES ('STA ISABEL IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALVORADA DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('BELA V PARAISO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAFEARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAMBE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CENTENARIO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('FLORESTOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUARACI');
INSERT INTO usuarios_cidade(cidade) VALUES ('IBIPORA');
INSERT INTO usuarios_cidade(cidade) VALUES ('JAGUAPITA');
INSERT INTO usuarios_cidade(cidade) VALUES ('LONDRINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('LUPIONOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('MIRASELVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PITANGUEIRAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PORECATU');
INSERT INTO usuarios_cidade(cidade) VALUES ('PRADO FERREIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PRIMEIRO MAIO');
INSERT INTO usuarios_cidade(cidade) VALUES ('ROLANDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SERTANOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('TAMARANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ANGULO');
INSERT INTO usuarios_cidade(cidade) VALUES ('ASTORGA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ATALAIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('COLORADO');
INSERT INTO usuarios_cidade(cidade) VALUES ('DOUTOR CAMARGO');
INSERT INTO usuarios_cidade(cidade) VALUES ('FLORAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('FLORESTA');
INSERT INTO usuarios_cidade(cidade) VALUES ('FLORIDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IGUARACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAMBE');
INSERT INTO usuarios_cidade(cidade) VALUES ('IVATUBA');
INSERT INTO usuarios_cidade(cidade) VALUES ('LOBATO');
INSERT INTO usuarios_cidade(cidade) VALUES ('MANDAGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('MANDAGUARI');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARIALVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARINGA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MUNHOZ DE MELLO');
INSERT INTO usuarios_cidade(cidade) VALUES ('N S DAS GRACAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('OURIZONA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PAICANDU');
INSERT INTO usuarios_cidade(cidade) VALUES ('PRES C BRANCO');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JORGE DO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA FE');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTO INACIO');
INSERT INTO usuarios_cidade(cidade) VALUES ('SARANDI');
INSERT INTO usuarios_cidade(cidade) VALUES ('ANTONINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUARAQUECABA');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUARATUBA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MATINHOS');
INSERT INTO usuarios_cidade(cidade) VALUES ('MORRETES');
INSERT INTO usuarios_cidade(cidade) VALUES ('PARANAGUA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PONTAL PARANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALTO PARANA');
INSERT INTO usuarios_cidade(cidade) VALUES ('AMAPORA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CRUZEIRO DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUAIRACA');
INSERT INTO usuarios_cidade(cidade) VALUES ('INAJA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAGUAJE');
INSERT INTO usuarios_cidade(cidade) VALUES ('JARDIM OLINDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MIRADOR');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA AL DO IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA ESPERANCA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PARAISO NORTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('PARANACITY');
INSERT INTO usuarios_cidade(cidade) VALUES ('PARANAPOEMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PARANAVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('S CARLOS IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA INES');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAO JOAO DO CAIUA');
INSERT INTO usuarios_cidade(cidade) VALUES ('STO ANT CAIUA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TAMBOARA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TERRA RICA');
INSERT INTO usuarios_cidade(cidade) VALUES ('UNIFLOR');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOM SUCESSO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CEL. D. SOARES');
INSERT INTO usuarios_cidade(cidade) VALUES ('CHOPINZINHO');
INSERT INTO usuarios_cidade(cidade) VALUES ('CLEVELANDIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CORONEL VIVIDA');
INSERT INTO usuarios_cidade(cidade) VALUES ('HONORIO SERPA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ITAPEJARA OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('MANGUEIRINHA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARIOPOLIS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PALMAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PATO BRANCO');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAO JOAO');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAUDADE IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('SULINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('VITORINO');
INSERT INTO usuarios_cidade(cidade) VALUES ('BOA V SAO ROQUE');
INSERT INTO usuarios_cidade(cidade) VALUES ('LARANJAL');
INSERT INTO usuarios_cidade(cidade) VALUES ('MATO RICO');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA TEBAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PALMITAL');
INSERT INTO usuarios_cidade(cidade) VALUES ('PITANGA');
INSERT INTO usuarios_cidade(cidade) VALUES ('STA MARIA OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CARAMBEI');
INSERT INTO usuarios_cidade(cidade) VALUES ('CASTRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('IMBITUVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IPIRANGA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IVAI');
INSERT INTO usuarios_cidade(cidade) VALUES ('PALMEIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PIRAI DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('PONTA GROSSA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PORTO AMAZONAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JOAO TRIUNFO');
INSERT INTO usuarios_cidade(cidade) VALUES ('TIBAGI');
INSERT INTO usuarios_cidade(cidade) VALUES ('CURIUVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IMBAU');
INSERT INTO usuarios_cidade(cidade) VALUES ('ORTIGUEIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('RESERVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAPOPEMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TELEMACO BORBA');
INSERT INTO usuarios_cidade(cidade) VALUES ('VENTANIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('DIAMANTE D OEST');
INSERT INTO usuarios_cidade(cidade) VALUES ('DIAMANTE DO OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('E RIOS OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('GUAIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MAL CAND RONDON');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARIPA');
INSERT INTO usuarios_cidade(cidade) VALUES ('MERCEDES');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA SANTA ROSA');
INSERT INTO usuarios_cidade(cidade) VALUES ('OURO VERDE OEST');
INSERT INTO usuarios_cidade(cidade) VALUES ('PALOTINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PATO BRAGADO');
INSERT INTO usuarios_cidade(cidade) VALUES ('QUATRO PONTES');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JOSE PALMEIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('S PEDRO IGUACU');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANTA HELENA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TERRA ROXA');
INSERT INTO usuarios_cidade(cidade) VALUES ('TOLEDO');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALTO PARAISO');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALTO PIQUIRI');
INSERT INTO usuarios_cidade(cidade) VALUES ('ALTONIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CAFEZAL DO SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('CRUZEIRO DO OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('CRUZEIRO OESTE');
INSERT INTO usuarios_cidade(cidade) VALUES ('DOURADINA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ESPERANCA NOVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('FRANCISCO ALVES');
INSERT INTO usuarios_cidade(cidade) VALUES ('ICARAIMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IPORA');
INSERT INTO usuarios_cidade(cidade) VALUES ('IVATE');
INSERT INTO usuarios_cidade(cidade) VALUES ('MARIA HELENA');
INSERT INTO usuarios_cidade(cidade) VALUES ('NOVA OLIMPIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('PEROBAL');
INSERT INTO usuarios_cidade(cidade) VALUES ('PEROLA');
INSERT INTO usuarios_cidade(cidade) VALUES ('S J PATROCINIO');
INSERT INTO usuarios_cidade(cidade) VALUES ('TAPIRA');
INSERT INTO usuarios_cidade(cidade) VALUES ('UMUARAMA');
INSERT INTO usuarios_cidade(cidade) VALUES ('XAMBRE');
INSERT INTO usuarios_cidade(cidade) VALUES ('ANTONIO OLINTO');
INSERT INTO usuarios_cidade(cidade) VALUES ('BITURUNA');
INSERT INTO usuarios_cidade(cidade) VALUES ('CRUZ MACHADO');
INSERT INTO usuarios_cidade(cidade) VALUES ('GAL CARNEIRO');
INSERT INTO usuarios_cidade(cidade) VALUES ('PAULA FREITAS');
INSERT INTO usuarios_cidade(cidade) VALUES ('PAULO FRONTIN');
INSERT INTO usuarios_cidade(cidade) VALUES ('PORTO VITORIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SAO MATEUS SUL');
INSERT INTO usuarios_cidade(cidade) VALUES ('UNIAO D VITORIA');
INSERT INTO usuarios_cidade(cidade) VALUES ('ARAPOTI');
INSERT INTO usuarios_cidade(cidade) VALUES ('JAGUARIAIVA');
INSERT INTO usuarios_cidade(cidade) VALUES ('S JOSE B VISTA');
INSERT INTO usuarios_cidade(cidade) VALUES ('SALTO ITARARE');
INSERT INTO usuarios_cidade(cidade) VALUES ('SANT DO ITARARE');
INSERT INTO usuarios_cidade(cidade) VALUES ('SENGES');
INSERT INTO usuarios_cidade(cidade) VALUES ('WENCESLAU BRAZ');
