# Generated by Django 2.2.6 on 2019-11-07 18:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('sexo', models.IntegerField(choices=[('1', 'Masculino'), ('2', 'Feminino')])),
                ('serie', models.CharField(choices=[('1', '1ª Ano'), ('2', '2ª Ano'), ('3', '3ª Ano'), ('4', '4ª Ano'), ('5', '5ª Ano'), ('6', '6ª Ano'), ('7', '7ª Ano'), ('8', '8ª Ano'), ('9', '9º Ano')], max_length=20)),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Cidade')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Escola')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
