# Generated by Django 2.2.7 on 2020-01-24 15:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['cidade'],
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=50)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Cidade')),
            ],
            options={
                'ordering': ['escola'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')])),
                ('serie', models.IntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano'), (4, '4º Ano'), (5, '5º Ano'), (6, '6º Ano'), (7, '7º Ano'), (8, '8º Ano'), (9, '9º Ano')])),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Cidade')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Escola')),
            ],
            options={
                'db_table': 'Usuario',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
