# Generated by Django 2.2.6 on 2019-10-05 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('sexo', models.IntegerField(choices=[('1', 'Masculino'), ('2', 'Feminino')])),
                ('serie', models.CharField(choices=[('1', '1ª Ano'), ('2', '2ª Ano'), ('3', '3ª Ano'), ('4', '4ª Ano'), ('5', '5ª Ano'), ('6', '6ª Ano'), ('7', '7ª Ano'), ('8', '8ª Ano'), ('9', '9º Ano')], max_length=20)),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Cidade')),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.Escola')),
            ],
        ),
    ]
