# Generated by Django 2.2.6 on 2019-11-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20191107_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='serie',
            field=models.IntegerField(choices=[('1', '1ª Ano'), ('2', '2ª Ano'), ('3', '3ª Ano'), ('4', '4ª Ano'), ('5', '5ª Ano'), ('6', '6ª Ano'), ('7', '7ª Ano'), ('8', '8ª Ano'), ('9', '9º Ano')], max_length=20),
        ),
    ]
