# Generated by Django 2.2.6 on 2019-11-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20191107_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='serie',
            field=models.IntegerField(choices=[(1, '1ª Ano'), (2, '2ª Ano'), (3, '3ª Ano'), (4, '4ª Ano'), (5, '5ª Ano'), (6, '6ª Ano'), (7, '7ª Ano'), (8, '8ª Ano'), (9, '9º Ano')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')]),
        ),
    ]
